"""Step 4 — assemble the final markdown brief.

Everything here is deterministic. The LLM's prose is dropped in as a block;
every number the reader sees is formatted straight from the snapshot.
"""

from __future__ import annotations

import logging
from datetime import date
from pathlib import Path

from .llm import Citation
from .market_data import MarketSnapshot, TickerSnapshot
from .research import ResearchBundle

log = logging.getLogger(__name__)


def _fmt_price(value: float | None) -> str:
    return f"{value:,.2f}" if value is not None else "—"


def _fmt_pct(value: float | None) -> str:
    return f"{value:+.2f}%" if value is not None else "—"


def _fmt_ratio(value: float | None) -> str:
    return f"{value:.2f}x" if value is not None else "—"


def _fmt_volume(value: float | None) -> str:
    if value is None:
        return "—"
    for cutoff, suffix in ((1e9, "B"), (1e6, "M"), (1e3, "K")):
        if abs(value) >= cutoff:
            return f"{value / cutoff:,.1f}{suffix}"
    return f"{value:,.0f}"


def price_table(snapshot: MarketSnapshot) -> str:
    """The numbers, rendered directly from the data."""

    rows = snapshot.ok_snapshots
    if not rows:
        return "_No market data was retrieved for this run._"

    header = (
        "| Ticker | Close | 1d | 5d | 21d | YTD | Volume | vs 20d avg | vs 52w high |\n"
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|"
    )
    lines = [header]
    for s in rows:
        lines.append(
            "| "
            + " | ".join(
                [
                    f"**{s.symbol}**",
                    _fmt_price(s.close),
                    _fmt_pct(s.change_pct),
                    _fmt_pct(s.change_5d_pct),
                    _fmt_pct(s.change_21d_pct),
                    _fmt_pct(s.change_ytd_pct),
                    _fmt_volume(s.volume),
                    _fmt_ratio(s.volume_ratio),
                    _fmt_pct(s.pct_from_52w_high),
                ]
            )
            + " |"
        )
    return "\n".join(lines)


def failures_block(snapshot: MarketSnapshot) -> str:
    failed = snapshot.failed_snapshots
    if not failed:
        return ""
    lines = ["**Tickers with no data this run:**", ""]
    lines += [f"- `{s.symbol}` — {s.error}" for s in failed]
    return "\n".join(lines)


def caveats_block(snapshot: MarketSnapshot, research: ResearchBundle) -> str:
    items = list(snapshot.warnings)
    items += research.errors
    if not items:
        return ""
    lines = ["**Caveats for this run:**", ""]
    lines += [f"- {item}" for item in items]
    return "\n".join(lines)


def sources_block(citations: list[Citation], limit: int = 30) -> str:
    if not citations:
        return ""
    lines = ["## Sources", ""]
    for cite in citations[:limit]:
        lines.append(f"- {cite.as_markdown()}")
    if len(citations) > limit:
        lines.append(f"- _…and {len(citations) - limit} more_")
    return "\n".join(lines)


def render_brief(
    snapshot: MarketSnapshot,
    research: ResearchBundle,
    prose: str,
    *,
    watchlist_name: str = "watchlist",
) -> str:
    """Assemble the full brief document."""

    session = snapshot.latest_session
    title_date = session.isoformat() if session else snapshot.status.now_et.date().isoformat()

    parts: list[str] = [
        f"# Daily brief — {title_date}",
        "",
        f"_{watchlist_name} · {len(snapshot.ok_snapshots)} of {len(snapshot.snapshots)} "
        f"tickers with data · generated {snapshot.generated_at.strftime('%Y-%m-%d %H:%M %Z')}_",
        "",
    ]

    # Blank lines between these, not just newlines — otherwise markdown
    # collapses them into one run-on paragraph.
    parts += [f"**Market status:** {snapshot.status.describe()}", ""]

    if session:
        parts.append(f"**Data through:** close of {session.isoformat()}")

    parts += ["", "---", "", prose.strip(), "", "---", "", "## The numbers", "", price_table(snapshot)]

    for block in (failures_block(snapshot), caveats_block(snapshot, research)):
        if block:
            parts += ["", block]

    sources = sources_block(research.citations)
    if sources:
        parts += ["", "---", "", sources]

    parts += [
        "",
        "---",
        "",
        "_Generated by briefbot. Phase 1: information only — no signals, no recommendations, "
        "no positions. Market data via yfinance (unofficial Yahoo Finance data); news and "
        "context synthesised by Claude with web search, and may be incomplete or wrong._",
        "",
    ]

    return "\n".join(parts)


def brief_path(output_dir: Path, session: date | None, generated: date) -> Path:
    stamp = (session or generated).isoformat()
    return output_dir / f"brief-{stamp}.md"


def write_brief(
    text: str,
    output_dir: Path,
    snapshot: MarketSnapshot,
    *,
    also_latest: bool = True,
) -> Path:
    """Write the brief to ``brief-YYYY-MM-DD.md`` plus a stable ``latest.md``."""

    output_dir.mkdir(parents=True, exist_ok=True)
    path = brief_path(output_dir, snapshot.latest_session, snapshot.generated_at.date())
    path.write_text(text, encoding="utf-8")
    log.info("wrote %s", path)

    if also_latest:
        # A failure here must not lose the dated brief that already landed.
        try:
            (output_dir / "latest.md").write_text(text, encoding="utf-8")
        except OSError as exc:
            log.warning("could not update latest.md: %s", exc)

    return path
